name: CI

on:
    workflow_call:

jobs:
    check_src:
        runs-on: ubuntu-24.04

        env:
            PUPPETEER_CACHE_DIR: ${{ github.workspace }}/node_modules/.chromium

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'

            - name: Format
              run: |
                  npm run format:src

            - name: Lint
              run: |
                  npm run lint:src

            - name: Type
              run: |
                  npm run type:src

            - name: Test
              run: |
                  npm test

    check_docs:
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.13'

            - name: Cache venv
              uses: actions/cache@v4
              with:
                  path: .venv
                  key: venv_ubuntu24_${{ hashFiles('pdm.lock') }}

            - name: Format
              run: |
                  source .venv/bin/activate
                  npm run format:docs

            - name: Lint
              run: |
                  source .venv/bin/activate
                  npm run lint:docs

    check_tools:
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.13'

            - name: Cache venv
              uses: actions/cache@v4
              with:
                  path: .venv
                  key: venv_ubuntu24_${{ hashFiles('pdm.lock') }}

            - name: Format
              run: |
                  source .venv/bin/activate
                  npm run format:tools

            - name: Lint
              run: |
                  source .venv/bin/activate
                  npm run lint:tools

            - name: Type
              run: |
                  source .venv/bin/activate
                  npm run type:tools
